import { addDays, subDays } from "date-fns";
import {
  Package,
  Warehouse,
  Truck,
  PackageCheck,
} from "lucide-react";

import type { Shipment } from "@/lib/types";

const now = new Date();

export const initialShipments: Shipment[] = [
  {
    id: "shipment-001",
    scancode: "SHP736482A",
    company: "Global Logistics",
    serviceType: "Express Air",
    status: "Delayed",
    timeline: [
      {
        id: "event-1-1",
        stage: "Booked",
        status: "completed",
        plannedDate: subDays(now, 8).toISOString(),
        actualDate: subDays(now, 8).toISOString(),
        comments: "",
        Icon: Package,
      },
      {
        id: "event-1-2",
        stage: "Pickup",
        status: "completed",
        plannedDate: subDays(now, 6).toISOString(),
        actualDate: subDays(now, 5).toISOString(),
        comments: "Carrier vehicle arrived late due to traffic congestion in the city center.",
        Icon: Warehouse,
      },
      {
        id: "event-1-3",
        stage: "In Transit",
        status: "in-progress",
        plannedDate: subDays(now, 2).toISOString(),
        actualDate: undefined,
        comments: "",
        Icon: Truck,
      },
      {
        id: "event-1-4",
        stage: "Delivered",
        status: "pending",
        plannedDate: addDays(now, 2).toISOString(),
        actualDate: undefined,
        comments: "",
        Icon: PackageCheck,
      },
    ],
  },
  {
    id: "shipment-002",
    scancode: "SHP298371B",
    company: "Speedy Shippers",
    serviceType: "Standard Ground",
    status: "On-Time",
    timeline: [
      {
        id: "event-2-1",
        stage: "Booked",
        status: "completed",
        plannedDate: subDays(now, 5).toISOString(),
        actualDate: subDays(now, 5).toISOString(),
        comments: "",
        Icon: Package,
      },
      {
        id: "event-2-2",
        stage: "Pickup",
        status: "completed",
        plannedDate: subDays(now, 4).toISOString(),
        actualDate: subDays(now, 4).toISOString(),
        comments: "",
        Icon: Warehouse,
      },
      {
        id: "event-2-3",
        stage: "In Transit",
        status: "in-progress",
        plannedDate: subDays(now, 1).toISOString(),
        actualDate: undefined,
        comments: "",
        Icon: Truck,
      },
      {
        id: "event-2-4",
        stage: "Delivered",
        status: "pending",
        plannedDate: addDays(now, 5).toISOString(),
        actualDate: undefined,
        comments: "",
        Icon: PackageCheck,
      },
    ],
  },
  {
    id: "shipment-003",
    scancode: "SHP555123C",
    company: "Quick Couriers",
    serviceType: "Next-Day",
    status: "Delivered",
    timeline: [
      {
        id: "event-3-1",
        stage: "Booked",
        status: "completed",
        plannedDate: subDays(now, 2).toISOString(),
        actualDate: subDays(now, 2).toISOString(),
        comments: "",
        Icon: Package,
      },
      {
        id: "event-3-2",
        stage: "Pickup",
        status: "completed",
        plannedDate: subDays(now, 2).toISOString(),
        actualDate: subDays(now, 2).toISOString(),
        comments: "",
        Icon: Warehouse,
      },
      {
        id: "event-3-3",
        stage: "In Transit",
        status: "completed",
        plannedDate: subDays(now, 1).toISOString(),
        actualDate: subDays(now, 1).toISOString(),
        comments: "",
        Icon: Truck,
      },
      {
        id: "event-3-4",
        stage: "Delivered",
        status: "completed",
        plannedDate: now.toISOString(),
        actualDate: subDays(now, 0).toISOString(),
        comments: "Recipient signed for the package.",
        Icon: PackageCheck,
      },
    ],
  },
];
